python extractElectronScaleFactorsFromRoot.py -f ../bamboo_/data/Inputs/2018UL/Egamma/egammaEffi_ptBelow20.txt_EGM2D_UL2018.root -s ptBelow20_UL2018
python extractElectronScaleFactorsFromRoot.py -f ../bamboo_/data/Inputs/2018UL/Egamma/egammaEffi_ptAbove20.txt_EGM2D_UL2018.root -s ptAbove20_UL2018
python extractElectronScaleFactorsFromRoot.py -f ../bamboo_/data/Inputs/2018UL/Egamma/egammaEffi.txt_Ele_Tight_EGM2D.root -s Run2018UL_Tight
python extractElectronScaleFactorsFromRoot.py -f ../bamboo_/data/Inputs/2018UL/Egamma/egammaEffi.txt_Ele_Medium_EGM2D.root -s Run2018UL_Medium
python extractElectronScaleFactorsFromRoot.py -f ../bamboo_/data/Inputs/2018UL/Egamma/egammaEffi.txt_Ele_Loose_EGM2D.root -s Run2018UL_Loose
python extractElectronScaleFactorsFromRoot.py -f ../bamboo_/data/Inputs/2018UL/Egamma/egammaEffi.txt_Ele_Veto_EGM2D.root -s Run2018UL_Veto
python extractElectronScaleFactorsFromRoot.py -f ../bamboo_/data/Inputs/2018UL/Egamma/egammaEffi.txt_Ele_wp80noiso_EGM2D.root -s Run2018UL_wp80noiso
python extractElectronScaleFactorsFromRoot.py -f ../bamboo_/data/Inputs/2018UL/Egamma/egammaEffi.txt_Ele_wp90noiso_EGM2D.root -s Run2018UL_wp90noiso
python extractElectronScaleFactorsFromRoot.py -f ../bamboo_/data/Inputs/2018UL/Egamma/egammaEffi.txt_Ele_wp80iso_EGM2D.root -s Run2018UL_wp80iso
python extractElectronScaleFactorsFromRoot.py -f ../bamboo_/data/Inputs/2018UL/Egamma/egammaEffi.txt_Ele_wp90iso_EGM2D.root -s Run2018UL_wp90iso
